server.port=8080

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/recruitment_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Houni el tasli7: nesta3mlou el dialect el 3am wala na77ih jemla
# khater Hibernate 6 yfahmou wa7dou
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Security Configuration
# Na77i hédhom khaterhom ma3adech ye5dmou s7i7 fil version jdidia
# spring.security.user.name=disable (Ghalta)